name: build debian package
on: [push]
jobs:
  build-debian-package:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get -qq update
      - run: sudo apt-get install python3.8 python3.8-dev python3-pip libcurl4 build-essential python3-tornado python3-setuptools debhelper dh-systemd cdbs dh-python fakeroot python3-pip rsync locales
      - run: pip3 install virtualenv
      - name: Create virtual python env
        run: virtualenv -p /usr/bin/python3.8 hotspot-env
      - name: Activate virtual python env
        run: source hotspot-env/bin/activate
      - name: Define build related environment variables
          run: |
            echo $SOURCE_NAME
            echo $SOURCE_BRANCH
            echo $SOURCE_TAG
          env:
            SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
            SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
            SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      - run: echo $SOURCE_NAME
      - run: echo $SOURCE_BRANCH
      - run: echo $SOURCE_TAG
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Set DATE ENV var
        run: CURRENT_DATE=$(date +%Y%m%d%H%M)
      - run: VERSION=$(head -1 debian/changelog | awk -F'[()]' '{print $2}')
      - run: sudo make deb
