name: build debian package
on: [push]
jobs:
  build-debian-package:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install python3.7 python3.7-dev libcurl3 build-essential python3-tornado python3-setuptools debhelper dh-systemd cdbs dh-python fakeroot python3-pip rsync locales
      - name: Create virtual python env
        run: virtualenv -p /usr/bin/python3.7 hotspot-env
      - name: Activate virtual python env
        run: source hotspot-env/bin/activate
      - name: Set DATE ENV var
        run: CURRENT_DATE=$(date +%Y%m%d%H%M)
      - run: VERSION=$(head -1 debian/changelog | awk -F'[()]' '{print $2}')
      - run: sudo make deb
